# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=16)),
                ('hobby', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=40)),
                ('birthday', models.DateField(default='1992-12-12')),
            ],
        ),
    ]
