# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='userxxx', max_length=30),
        ),
    ]
