# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160328_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.AddField(
            model_name='user',
            name='label',
            field=models.CharField(default='news', max_length=40),
            preserve_default=False,
        ),
    ]
